### PR TITLE
Added my presentations

### PR DESCRIPTION
**Pull request by vittorioromeo**
I've added my ECS presentations as a `.pdf` file, but since the second talk (the "static control flow" one) is code-only, I've added a text file pointing to the GitHub repository - hope that's OK.

### CODE REVIEW

**Comment by brycelelbach** [comment]
I think it might be better to just have the table of contents link to the github repo for the second one.

**Comment by vittorioromeo** [comment]
Is it fine now?

**Comment by brycelelbach** [comment]
Should be fine, there's a conflict though (probably because I accepted a new pull request). If you have a moment, can you rebase and resolve the conflict? If not I can do it.

**Comment by vittorioromeo** [comment]
Done.

**Pull request merged**
